#!/bin/bash
echo "The script is designed to do the following tasks: "
echo ""
echo "Add User: Adds a new user to the system."
echo "Modify User: Changes the comment of an existing user."
echo "Delete User: Deletes an existing user from the system."
echo "List Users: Lists all users on the system."
echo "Add Group: Adds a new user group to the system."
echo "Modify Group: Changes group & list of its members."
echo "Add user to group: adds a user to an existing group on the system."
echo "List Groups: Lists all existing groups on the system."
echo "Disable User: Lock the user account."
echo "Enable User: UnLock the user account."
echo "Change Password: Changes the password of an existing user."
echo ""
echo "<<<<<<<<<<<<<<<<<<<<<<<<<Created By: Abdulrahman Elfeki>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
echo "Date:$(date)"

